describe('RXP Portal',()=>{
    beforeEach(() => {
        cy.visit("https://portal.etsn.az/")
    })
    it('firstmenu',()=>{
        //cy.visit("https://test-portal.etsn.az/")
        cy.wait(2500)
        cy.get('.ant-input').type("Ovçuluq biletinin verilməsi")
        cy.get('.banner_search-result_item__AOJ7k').click()
        cy.wait(3000)
        cy.get('.title_title__gDsuB').should('include.text', 'Ovçuluq')
        cy.get('.description-container > :nth-child(8)').should('include.text', '25')
        cy.get(':nth-child(14) > a').invoke('removeAttr','target').click({force:true})
        })


    it('parts',()=>{
        // cy.visit("https://test-portal.etsn.az/")
        cy.wait(2500)
        cy.get(':nth-child(1) > .p-0 > .info-card_info-card_inner__I5i5g > .info-card_info-card_link__iuc8x > span.mt-10').click()
        cy.get('.tab_active__oNuqv > .tab_tabs-header__mxZAD').click()
        cy.get('.ant-pagination-item-2 > a').click()
        cy.get(':nth-child(1) > a > .result-list_result-list_item__F29YJ > .result-list_item-inner__bLVA_ > div > span').click()
        cy.get('.title_title__gDsuB').should('include.text', 'Ehtiyatları təsdiq edilmiş faydalı qazıntı yataqlarının yerləşdiyi dövlət və bələdiyyə mülkiyyətində olan torpaqların mülkiyyətə, istifadəyə və ya icarəyə verilməsinə dair rəyin verilməsi')
        cy.go(-2)
        cy.wait(6500)
        cy.get('a.mt-25 > .ml-10').click({ multiple: true })
        cy.wait(6500)
        cy.get(':nth-child(1) > a > .p-0').click()
        cy.get('.tab_active__oNuqv').click()
        cy.get(':nth-child(1) > .result-list_result-list_item__F29YJ > a > .d-flex > p').click()
        cy.go(-2)
        cy.get('.footer_footer-list__WGUVs > .d-flex > :nth-child(1) > a').click()
        cy.wait(2000)
        cy.get('.col-md-9 > .title_title__gDsuB').should('include.text','Portalın üstünlükləri?')
        cy.go(-1)
        cy.get('.d-flex > :nth-child(4) > a').click()
        cy.wait(2000)
        cy.get('.support_support-links__pjCDm > :nth-child(2) > .ml-10').click()
        cy.get('#phone').type("(055)-440-27-03")
        cy.get('.ant-modal-footer > .ant-btn').click()
        })
    })